// =========================================================================
// Mindora — Supabase database types
// =========================================================================
// Mirrors supabase/migrations/20260529000001_initial_schema.sql exactly.
// Generated by hand for now — once the project is provisioned, this file
// can be regenerated with:
//   npx supabase gen types typescript --project-id <id> > src/types/database.ts
// =========================================================================

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      // ─── profiles ──────────────────────────────────────────────────
      profiles: {
        Row: {
          id: string;             // uuid (auth.users.id)
          email: string | null;
          name: string | null;
          avatar_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email?: string | null;
          name?: string | null;
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["profiles"]["Insert"]>;
        Relationships: [];
      };

      // ─── workspaces ────────────────────────────────────────────────
      workspaces: {
        Row: {
          id: string;
          owner_id: string;       // uuid
          name: string;
          type: "personal" | "team";
          color: string;
          member_count: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          owner_id: string;
          name: string;
          type: "personal" | "team";
          color: string;
          member_count?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["workspaces"]["Insert"]>;
        Relationships: [];
      };

      // ─── workspace_members ─────────────────────────────────────────
      workspace_members: {
        Row: {
          id: string;
          workspace_id: string;
          user_id: string | null;
          name: string;
          email: string | null;
          role: "owner" | "member";
          added_at: string;
        };
        Insert: {
          id: string;
          workspace_id: string;
          user_id?: string | null;
          name: string;
          email?: string | null;
          role: "owner" | "member";
          added_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["workspace_members"]["Insert"]>;
        Relationships: [];
      };

      // ─── projects ──────────────────────────────────────────────────
      projects: {
        Row: {
          id: string;
          workspace_id: string;
          name: string;
          color: string;
          icon: string;
          icon_url: string | null;
          type: "general" | "video" | "design";
          shared_workspace_ids: string[];
          position: number;
          created_at: string;
        };
        Insert: {
          id: string;
          workspace_id: string;
          name: string;
          color: string;
          icon: string;
          icon_url?: string | null;
          type: "general" | "video" | "design";
          shared_workspace_ids?: string[];
          position?: number;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["projects"]["Insert"]>;
        Relationships: [];
      };

      // ─── categories ────────────────────────────────────────────────
      categories: {
        Row: {
          id: string;
          workspace_id: string;
          name: string;
          color: string;
          type: "general" | "video" | "design";
          description: string | null;
          created_at: string;
        };
        Insert: {
          id: string;
          workspace_id: string;
          name: string;
          color: string;
          type: "general" | "video" | "design";
          description?: string | null;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["categories"]["Insert"]>;
        Relationships: [];
      };

      // ─── tags ──────────────────────────────────────────────────────
      tags: {
        Row: {
          id: string;
          workspace_id: string;
          name: string;
          color: string;
          description: string | null;
          created_at: string;
        };
        Insert: {
          id: string;
          workspace_id: string;
          name: string;
          color: string;
          description?: string | null;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["tags"]["Insert"]>;
        Relationships: [];
      };

      // ─── tasks ─────────────────────────────────────────────────────
      tasks: {
        Row: {
          id: string;
          workspace_id: string;
          project_id: string | null;
          category_id: string | null;
          title: string;
          notes: string;
          tag_ids: string[];
          priority: "low" | "medium" | "high" | "urgent";
          status: "todo" | "in_progress" | "done" | "cancelled";
          column: "backlog" | "this_week" | "today" | "done";
          position: number;
          estimated_minutes: number | null;
          actual_minutes: number;
          deadline: string | null;        // ISO date (YYYY-MM-DD)
          video_stage:
            | "idea" | "script" | "filming" | "editing" | "scheduled" | "published"
            | null;
          links: Array<{ label: string; url: string }>;
          completed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          workspace_id: string;
          project_id?: string | null;
          category_id?: string | null;
          title: string;
          notes?: string;
          tag_ids?: string[];
          priority: "low" | "medium" | "high" | "urgent";
          status: "todo" | "in_progress" | "done" | "cancelled";
          column: "backlog" | "this_week" | "today" | "done";
          position?: number;
          estimated_minutes?: number | null;
          actual_minutes?: number;
          deadline?: string | null;
          video_stage?:
            | "idea" | "script" | "filming" | "editing" | "scheduled" | "published"
            | null;
          links?: Array<{ label: string; url: string }>;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["tasks"]["Insert"]>;
        Relationships: [];
      };

      // ─── schedule_posts ────────────────────────────────────────────
      schedule_posts: {
        Row: {
          id: string;
          workspace_id: string;
          task_id: string | null;
          title: string;
          notes: string;
          platforms: string[];
          tags: string[];
          links: Array<{ label: string; url: string }>;
          scheduled_date: string | null;  // "MM-DD"
          scheduled_time: string | null;  // "HH:MM"
          column: "content" | "this_week" | "today" | "published";
          position: number;
          preview_image_url: string | null;
          created_at: string;
        };
        Insert: {
          id: string;
          workspace_id: string;
          task_id?: string | null;
          title: string;
          notes?: string;
          platforms?: string[];
          tags?: string[];
          links?: Array<{ label: string; url: string }>;
          scheduled_date?: string | null;
          scheduled_time?: string | null;
          column: "content" | "this_week" | "today" | "published";
          position?: number;
          preview_image_url?: string | null;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["schedule_posts"]["Insert"]>;
        Relationships: [];
      };

      // ─── meetings ──────────────────────────────────────────────────
      meetings: {
        Row: {
          id: string;
          workspace_id: string;
          title: string;
          date: string;                   // ISO date (YYYY-MM-DD)
          time: string | null;            // "HH:MM"
          duration_minutes: number | null;
          location: string;
          notes: string;
          attendees: string[];
          meeting_link: string | null;
          source: "manual" | "google";
          external_id: string | null;
          created_at: string;
        };
        Insert: {
          id: string;
          workspace_id: string;
          title: string;
          date: string;
          time?: string | null;
          duration_minutes?: number | null;
          location?: string;
          notes?: string;
          attendees?: string[];
          meeting_link?: string | null;
          source?: "manual" | "google";
          external_id?: string | null;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["meetings"]["Insert"]>;
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: {
      is_workspace_accessible: {
        Args: { ws_id: string };
        Returns: boolean;
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
